#!/bin/sh
FILTERS=
ARGS=
for arg in "$@"
do
    echo $arg
    case $arg in
        -*) ARGS="$ARGS $arg" ;;
        *)
            if [ -z $FILTERS ]; then
                FILTERS=$arg
            else
                FILTERS="$FILTERS:$arg"
            fi
            ;;
    esac
done
if [ ! -z $FILTERS ]; then
    ARGS="$ARGS --gtest_filter=$FILTERS"
fi
./pkcs11test -m libchaps.so.0 -l /usr/lib -u 111111 $ARGS
