#!/bin/sh
FILTERS=
ARGS=
PREFIX=
for arg in "$@"
do
    case $arg in
        -gdb) PREFIX="gdb --args" ;;
        -*) ARGS="$ARGS $arg" ;;
        *)
            if [ -z $FILTERS ]; then
                FILTERS=$arg
            else
                FILTERS="$FILTERS:$arg"
            fi
            ;;
    esac
done
if [ ! -z $FILTERS ]; then
    ARGS="$ARGS --gtest_filter=$FILTERS"
fi
$PREFIX ./pkcs11test -m libchaps.so.0 -l /usr/lib -u 111111 -X $ARGS
