#!/bin/sh
FILTERS=
ARGS=
PREFIX=
for arg in "$@"
do
    case $arg in
        -gdb) PREFIX="gdb --args" ;;
        -*) ARGS="$ARGS $arg" ;;
        *)
            if [ -z $FILTERS ]; then
                FILTERS=$arg
            else
                FILTERS="$FILTERS:$arg"
            fi
            ;;
    esac
done
if [ ! -z $FILTERS ]; then
    ARGS="$ARGS --gtest_filter=$FILTERS"
fi
$PREFIX ./pkcs11test -m libopencryptoki.so -l /usr/lib/opencryptoki -s 0 $ARGS
